# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  format_listener:
    rules:
      - { path: ^/, fallback_format: json, priorities: [ json ] }
  exception:
    enabled: true
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true